[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "auth>=0.5.3",
    "fake-http-header>=0.3.5",
    "termcolor>=3.1.0",
]
